### ISSUE TITLE
Error message regarding Ads API v14

### ISSUE THREAD

**Issue by LarsMaat** [google-marketing-solutions/adios#47]
Hi,

I've got access to the Basic Ads API so I have a token. But when I run the script, I get this error message which seems to implicate that the API needs to be updated:

Error: {"code":400,"message":"Request contains an invalid argument.","status":"INVALID_ARGUMENT","details":[{"@type":"type.googleapis.com/google.ads.googleads.v14.errors.GoogleAdsFailure","errors":[{"errorCode":{"requestError":"UNSUPPORTED_VERSION"},"message":"**Version v14 is deprecated.** Requests to this version will be blocked."}],"requestId":"qUu3ZSMS9jDpnmuJSBBbLA"}]}

Because of the bold text (v14 version) I think it is an error regarding the Ads API version but not sure if I need to do something regarding my Ads API or that it's regarding the Adios system?

**Comment by Pitcocy** [comment]
Hi, 

I got the same error today - I couldn't find a solution on my end.

**Comment by LarsMaat** [comment]
Great news. I do not see the error message anymore. But I know have: SyntaxError: Unexpected token 'N', "Not Found" is not valid JSON





Lars Maat
Online Marketing Strateeg & Kwaliteitsmanager
Make an impact and inspire others to do the same!
​Wij leveren impact - Wij inspireren - Wij zijn Maatjes
Bezoekadres
Telefoon privé
Telefoon algemeen
Mobiel
Website
Goudsesingel 190, 3011 KD Rotterdam
010 30 38 902
010 30 30 222
06 30 33 06 12
www.maatwerkonline.nl
Van: Andriy Kushnarov ***@***.***>
Verzonden: woensdag 3 juli 2024 11:47
Aan: google-marketing-solutions/adios ***@***.***>
CC: Lars Maat van Maatwerk Online ***@***.***>; Author ***@***.***>
Onderwerp: Re: [google-marketing-solutions/adios] Error message regarding Ads API v14 (Issue #47)

U ontvangt niet vaak e-mail van ***@***.******@***.***>. Meer informatie over waarom dit belangrijk is<https://aka.ms/LearnAboutSenderIdentification>

Hi everyone,

We're thrilled to announce the release of Adios v1.2! This new version now leverages the power of Google Ads API v17. We appreciate your patience during the development process.

-
